/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./booking.html",
    "./legal.html",
    "./legal/*.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002023",
        "primary-fixed-dim": "#5cd7e4",
        "on-tertiary-fixed-variant": "#0d4e54",
        "on-error": "#690005",
        "primary": "#5cd7e4",
        "on-error-container": "#ffdad6",
        "background": "#131313",
        "secondary-fixed": "#97f1fd",
        "tertiary-fixed-dim": "#98d0d7",
        "outline": "#869395",
        "secondary-container": "#007984",
        "inverse-on-surface": "#313030",
        "error": "#ffb4ab",
        "surface-container-highest": "#353534",
        "secondary-fixed-dim": "#7ad4e0",
        "on-tertiary-container": "#003337",
        "inverse-primary": "#006971",
        "surface-bright": "#3a3939",
        "inverse-surface": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#01a4b0",
        "primary-fixed": "#84f3ff",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#00363c",
        "surface-container": "#201f1f",
        "surface-tint": "#5cd7e4",
        "outline-variant": "#3d494a",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed": "#002023",
        "on-primary": "#00363b",
        "tertiary": "#98d0d7",
        "error-container": "#93000a",
        "on-primary-container": "#003337",
        "surface-variant": "#353534",
        "on-secondary-container": "#caf8ff",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "tertiary-container": "#669da4",
        "secondary": "#7ad4e0",
        "on-tertiary": "#00363b",
        "on-primary-fixed-variant": "#004f55",
        "on-secondary-fixed": "#001f23",
        "on-surface-variant": "#bcc9ca",
        "tertiary-fixed": "#b3ecf3",
        "on-secondary-fixed-variant": "#004f56",
        "surface": "#131313"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
